
spring:
  ai:
    dashscope:
      api-key: sk-8959453f76ca4902843572da31d9feb1
      chat:
        options:
          model: deepseek-r1
  application:
    name: heima-ai
server:
  port: 8080
logging:
  level:
    com.itheima.heimaai: DEBUG
