#debug: true

spring:
  config:
    import: classpath:llm.yml
  ai:
    openai:
      base-url: https://api.v3.cm #OpenAI 地址(暂时不用，聊天模型在llm.yml中配置)
      api-key: sk-JJHRH4tZwO7vZ21p5b14104c78424c4a9bA036Da75Bb1f86 #OpenAI API Key
    vectorstore:
      pgvector:
        initialize-schema: true
        table-name: vector_store_1024
        remove-existing-vector-store-table: false
        dimensions: 1024
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5433/springaialibaba
  data:
    redis:
      host: localhost  # Redis服务器地址
      port: 6379  # Redis服务器连接端口
      password: 123456 # Redis服务器连接密码（默认为空）
      database: 0  # 0-15
      timeout: 10s # 连接超时时间
      lettuce:
        pool:
          max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 8 # 连接池最大空闲连接数
          min-idle: 0 # 连接池最小空闲连接数
          max-wait: -1ms   # 连接池最大阻塞等待时间（使用负值表示没有限制）

# MinIO
minio:
  endpoint: http://127.0.0.1:9000/
  access-key: minio
  secret-key: minio123
  default-bucket: springaialibaba
  default-expiry: 3600 # 临时访问连接1h有效 60 * 6