#debug: true

spring:
  config:
    import: classpath:llm.yml
  ai:
    openai:
      base-url: https://api.mnzdna.xyz
      api-key: sk-KgvugzpKzki15GFxB72e7782De844b23B3E4Fc6dDf40B29a
    vectorstore:
      pgvector:
        initialize-schema: true
        table-name: vector_store_1536
        remove-existing-vector-store-table: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5433/springaialibaba

# MinIO
minio:
  endpoint: http://127.0.0.1:9000/
  access-key: admin
  secret-key: admin123
  default-bucket: permission-demo
  default-expiry: 3600 # 临时访问连接1h有效 60 * 6