version: '3.9'
services:
  pgvector:
    image: pgvector/pgvector:pg17
    ports:
      - '5433:5432'
    volumes:
      - './postgresql_data:/var/lib/postgresql/data'  # 使用相对路径
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: vector_db
      PGDATA: /var/lib/postgresql/data/pgdata  # 明确数据目录
    restart: unless-stopped  # 更灵活的重启策略
    networks:
      - vector-net

  minio:
    image: minio/minio
    hostname: minio
    ports:
      - '9000:9000'  # S3 API端口
      - '9001:9001'  # 控制台端口
    environment:
      MINIO_ROOT_USER: minio       # 增强安全性
      MINIO_ROOT_PASSWORD: minio123
      MINIO_DOMAIN: localhost
    volumes:
      - './minio/data:/data'          # 数据卷使用相对路径
      - './minio/config:/root/.minio' # 配置目录
    command: server --console-address ':9001' /data  # 指定控制台端口
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    networks:
      - vector-net

networks:
  vector-net:
    driver: bridge
# Mac上的docker-compose命令
#docker-compose up -d