version: '3.9'
services:
  pgvector:
    image: 'pgvector/pgvector:pg17'
    ports:
      - '5433:5432'
    volumes:
      - '/Users/hllqk/docker/postgresql_pgvector/data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    restart: always
    container_name: pgvector
# Mac上依次运行(安装postgresql和pgvector):
#mkdir -p /Users/hllqk/docker/postgresql_pgvector/data
#docker-compose up -d